version: "3"
services:

  webapi:
    image: mrinalkamboj/hwapisync:latest
    ports:
      - "5001:80"
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    
  visualizer:
    image: dockersamples/visualizer:stable
    ports: 
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  backend: